server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: cambio-service
        uri: lb://cambio-service
        predicates:
        - Path=/cambio-service/**
      - id: book-service
        uri: lb://book-service
        predicates:
        - Path=/book-service/**
      - id: openapi
        uri: lb://api-gateway
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs


#  https://medium.com/@pubuduc.14/swagger-openapi-specification-3-integration-with-spring-cloud-gateway-part-2-1d670d4ab69a
#server:
#  servlet:
#    context-path: /
#  port:
#    8080
#spring:
#  profiles:
#    active:
#      - ${ACTIVE_SPRING_PROFILE:dev}
#  application:
#    name: api-gateway-service
#springdoc:
##  enable-native-support: true
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
#    path: /swagger-ui.html
#    config-url: /v3/api-docs/swagger-config
#    urls:
#      - url: /v3/api-docs
#        name: API Gateway Service
##        primaryName: API Gateway Service
#      - url: /cambio-service/v3/api-docs
#        name: Cambio Service
##        primaryName: Product Service
#      - url: /book-service/v3/api-docs
#        name: Book Service
##        primaryName: Price Service
